name: clabtoolkit-env
channels:
    - defaults
    - conda-forge
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
dependencies:
    - _libgcc_mutex
    - _openmp_mutex
    - pip
    - itables
    - asttokens
    - bzip2
    - ca-certificates
    - comm
    - debugpy
    - decorator
    - exceptiongroup
    - executing
    - expat
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython_pygments_lexers
    - jedi
    - jupyter_client
    - jupyter_core
    - krb5
    - ld_impl_linux-64
    - libedit
    - libffi
    - libgcc
    - libgcc-ng
    - libgomp
    - libsodium
    - libstdcxx
    - libstdcxx-ng
    - libuuid
    - matplotlib-inline
    - ncurses
    - nest-asyncio
    - openssl
    - parso
    - pexpect
    - pickleshare
    - platformdirs
    - prompt-toolkit
    - psutil
    - ptyprocess
    - pure_eval
    - python=3.12
    - python-dateutil
    - pyzmq
    - readline
    - six
    - sqlite
    - stack_data
    - tk
    - tornado
    - traitlets
    - wcwidth
    - wheel
    - xz
    - zeromq
    - zipp
    - zlib
    - pip:
          - alabaster
          - altair
          - annotated-types
          - anyio
          - argon2-cffi
          - argon2-cffi-bindings
          - arrow
          - async-lru
          - attrs
          - babel
          - beautifulsoup4
          - binaryornot
          - bleach
          - blinker
          - brotli
          - build
          - cachetools
          - certifi
          - cffi
          - chardet
          - charset-normalizer
          - citeproc-py
          - click
          - colorama
          - contourpy
          - cycler
          - dataclasses-json
          - defusedxml
          - deprecated
          - devicetorch
          - dipy
          - docutils
          - duecredit
          - et-xmlfile
          - fastapi
          - fastjsonschema
          - ffmpy
          - filelock
          - fonttools
          - fqdn
          - frozenlist
          - fsspec
          - fury
          - gitdb
          - gitpython
          - groovy
          - h11
          - h5py
          - hf-xet
          - httpcore
          - httpx
          - huggingface-hub
          - idna
          - imageio
          - imagesize
          - iniconfig
          - ipython-genutils
          - ipywidgets
          - isoduration
          - jinja2
          - jinja2-time
          - joblib
          - json5
          - jsonpointer
          - jsonschema
          - jsonschema-specifications
          - jupyter-events
          - jupyter-lsp
          - jupyter-server
          - jupyter-server-terminals
          - jupyterlab
          - jupyterlab-pygments
          - jupyterlab-server
          - jupyterlab-widgets
          - kiwisolver
          - lazy-loader
          - looseversion
          - lxml
          - markdown-it-py
          - markupsafe
          - marshmallow
          - matplotlib
          - mdit-py-plugins
          - mdurl
          - mistune
          - more-itertools
          - mpmath
          - msgpack
          - multidict
          - mycolorpy
          - mypy-extensions
          - myst-parser
          - narwhals
          - nbclient
          - nbconvert
          - nbformat
          - networkx
          - nibabel
          - nigsp
          - nilearn
          - ninja
          - notebook
          - notebook-shim
          - numpy
          - nvidia-cublas-cu12
          - nvidia-cuda-cupti-cu12
          - nvidia-cuda-nvrtc-cu12
          - nvidia-cuda-runtime-cu12
          - nvidia-cudnn-cu12
          - nvidia-cufft-cu12
          - nvidia-curand-cu12
          - nvidia-cusolver-cu12
          - nvidia-cusparse-cu12
          - nvidia-nccl-cu12
          - nvidia-nvjitlink-cu12
          - nvidia-nvtx-cu12
          - openpyxl
          - orderly-set
          - orjson
          - overrides
          - packaging
          - pandas
          - pandas-flavor
          - pandocfilters
          - patsy
          - pillow
          - pingouin
          - pip
          - pluggy
          - pooch
          - prometheus-client
          - propcache
          - protobuf
          - pyarrow
          - pycparser
          - pydantic
          - pydantic-core
          - pydeck
          - pydicom
          - pydub
          - pygame
          - pygltflib
          - pygments
          - pyparsing
          - pyproject-hooks
          - pytest
          - python-json-logger
          - python-multipart
          - python-slugify
          - pytz
          - pyvista
          - pyyaml
          - referencing
          - regex
          - requests
          - rfc3339-validator
          - rfc3986-validator
          - rich
          - roman-numerals-py
          - rpds-py
          - ruff
          - safehttpx
          - safetensors
          - scikit-image
          - scikit-learn
          - scipy
          - scooby
          - screeninfo
          - seaborn
          - semantic-version
          - send2trash
          - sentencepiece
          - setuptools
          - setuptools-scm
          - shellingham
          - smmap
          - sniffio
          - snowballstemmer
          - soupsieve
          - sphinx
          - sphinx-rtd-theme
          - sphinxcontrib-applehelp
          - sphinxcontrib-devhelp
          - sphinxcontrib-htmlhelp
          - sphinxcontrib-jquery
          - sphinxcontrib-jsmath
          - sphinxcontrib-qthelp
          - sphinxcontrib-serializinghtml
          - starlette
          - statsmodels
          - streamlit
          - sympy
          - tabulate
          - tenacity
          - terminado
          - text-unidecode
          - threadpoolctl
          - tifffile
          - tinycss2
          - tokenizers
          - toml
          - tomlkit
          - tqdm
          - trame
          - trame-client
          - trame-common
          - trame-jupyter-extension
          - trame-server
          - trame-vtk
          - trame-vuetify
          - trx-python
          - typer
          - types-python-dateutil
          - typing-extensions
          - typing-inspect
          - typing-inspection
          - tzdata
          - uri-template
          - urllib3
          - uvicorn
          - vtk
          - watchdog
          - webcolors
          - webencodings
          - websocket-client
          - websockets
          - widgetsnbextension
          - wrapt
          - wslink
          - xarray
          - xformers
          - yarl
