name: clabtoolkit-env
channels:
    - conda-forge
    - defaults
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
dependencies:
    - asttokens
    - bzip2
    - pip
    - itables
    - ca-certificates
    - comm
    - debugpy
    - decorator
    - exceptiongroup
    - executing
    - expat
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython_pygments_lexers
    - jedi
    - jupyter_client
    - jupyter_core
    - krb5
    - libedit
    - libffi
    - libkrb5
    - libsodium
    - libuuid
    - libxcb
    - lmdb
    - matplotlib-inline
    - ncurses
    - nest-asyncio
    - openssl
    - parso
    - pexpect
    - pickleshare
    - platformdirs
    - prompt-toolkit
    - prompt_toolkit
    - psutil
    - pthread-stubs
    - ptyprocess
    - pure_eval
    - python=3.12
    - python-dateutil
    - pyzmq
    - readline
    - six
    - sqlite
    - stack_data
    - tk
    - tornado
    - traitlets
    - wcwidth
    - wheel
    - xorg-libx11
    - xorg-libxau
    - xorg-libxdmcp
    - xorg-xorgproto
    - xz
    - zeromq
    - zipp
    - zlib
    - pip:
          - aiohappyeyeballs
          - aiohttp
          - aiosignal
          - alabaster
          - annotated-types
          - anyio
          - argon2-cffi
          - argon2-cffi-bindings
          - arrow
          - async-lru
          - attrs
          - babel
          - beautifulsoup4
          - bleach
          - brotli
          - cachebox
          - certifi
          - cffi
          - chardet
          - charset-normalizer
          - click
          - colorama
          - contourpy
          - cycler
          - dataclasses-json
          - deepdiff
          - defusedxml
          - deprecated
          - dipy
          - docutils
          - fastjsonschema
          - filelock
          - fonttools
          - fqdn
          - frozenlist
          - fsspec
          - fury
          - h11
          - h5py
          - httpcore
          - httpx
          - idna
          - imageio
          - imagesize
          - iniconfig
          - ipython-genutils
          - ipywidgets
          - isoduration
          - jinja2
          - joblib
          - json5
          - jsonpointer
          - jsonschema
          - jsonschema-specifications
          - jupyter-events
          - jupyter-lsp
          - jupyter-server
          - jupyter-server-terminals
          - jupyterlab
          - jupyterlab-pygments
          - jupyterlab-server
          - jupyterlab-widgets
          - kiwisolver
          - lazy-loader
          - looseversion
          - lxml
          - markdown-it-py
          - markupsafe
          - marshmallow
          - matplotlib
          - mdit-py-plugins
          - mdurl
          - mistune
          - more-itertools
          - msgpack
          - multidict
          - mypy-extensions
          - myst-parser
          - nbclient
          - nbconvert
          - nbformat
          - networkx
          - nibabel
          - nilearn
          - notebook
          - notebook-shim
          - numpy
          - orderly-set
          - overrides
          - packaging
          - pandas
          - pandocfilters
          - pillow
          - pip
          - pluggy
          - pooch
          - prometheus-client
          - propcache
          - pycparser
          - pydantic
          - pydantic-core
          - pydicom
          - pygltflib
          - pygments
          - pyparsing
          - pytest
          - python-json-logger
          - pytz
          - pyvista
          - pyyaml
          - referencing
          - regex
          - requests
          - rfc3339-validator
          - rfc3986-validator
          - rich
          - roman-numerals-py
          - rpds-py
          - scikit-image
          - scikit-learn
          - scipy
          - scooby
          - screeninfo
          - send2trash
          - setuptools
          - setuptools-scm
          - shellingham
          - sniffio
          - snowballstemmer
          - soupsieve
          - sphinx
          - sphinx-rtd-theme
          - sphinxcontrib-applehelp
          - sphinxcontrib-devhelp
          - sphinxcontrib-htmlhelp
          - sphinxcontrib-jquery
          - sphinxcontrib-jsmath
          - sphinxcontrib-qthelp
          - sphinxcontrib-serializinghtml
          - tabulate
          - terminado
          - threadpoolctl
          - tifffile
          - tinycss2
          - tqdm
          - trame
          - trame-client
          - trame-common
          - trame-jupyter-extension
          - trame-server
          - trame-vtk
          - trame-vuetify
          - trx-python
          - typer
          - typing-extensions
          - typing-inspect
          - typing-inspection
          - tzdata
          - uri-template
          - urllib3
          - vtk
          - webcolors
          - webencodings
          - websocket-client
          - websockets
          - widgetsnbextension
          - wrapt
          - wslink
          - yarl
